services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_container
    restart: always
    environment:
      - 'POSTGRES_DB=spribe'
      - 'POSTGRES_USER=spribe_user'
      - 'POSTGRES_PASSWORD=spribe_password'
    ports:
      - '5432:5432'
#    volumes:
#      - /Users/mikle/postgres/spribe:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: redis_container
    restart: always
    ports:
      - '6379:6379'
#    volumes:
#      - /Users/mikle/redis/data:/data
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--notify-keyspace-events", "Ex"
    ]
