spring:

  application:
    name: bookingsystem

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spribe
    username: spribe_user
    password: spribe_password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
app:
  payment:
    expiration-time: 15
    time-unit: MINUTES

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
